"""remove duration and add start and end time

Revision ID: 0348814d067d
Revises: 1d0db7da3842
Create Date: 2023-09-09 15:23:23.506174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0348814d067d'
down_revision = '1d0db7da3842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('StartTime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('EndTime', sa.Time(), nullable=False))
        batch_op.drop_column('Duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Duration', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('EndTime')
        batch_op.drop_column('StartTime')

    # ### end Alembic commands ###
