"""empty message

Revision ID: 06f86b1af5f6
Revises: 
Create Date: 2023-08-27 00:51:08.819206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f86b1af5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExtensionProgram',
    sa.Column('ExtensionProgramId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('Agenda', sa.String(length=100), nullable=False),
    sa.Column('Program', sa.String(length=100), nullable=False),
    sa.Column('DateApproved', sa.Date(), nullable=False),
    sa.Column('ImplementationDate', sa.Date(), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ExtensionProgramId')
    )
    op.create_table('Role',
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('RoleName', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('RoleId')
    )
    op.create_table('Login',
    sa.Column('LoginId', sa.String(length=36), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Password', sa.String(length=60), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['Role.RoleId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('LoginId'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Project',
    sa.Column('ProjectId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.Column('LeadProponent', sa.String(length=255), nullable=False),
    sa.Column('ProjectType', sa.String(length=100), nullable=False),
    sa.Column('Rationale', sa.String(length=255), nullable=False),
    sa.Column('Objectives', sa.String(length=255), nullable=False),
    sa.Column('NumberOfBenificiaries', sa.Integer(), nullable=False),
    sa.Column('BeneficiariesClassifications', sa.String(length=255), nullable=False),
    sa.Column('ProjectScope', sa.String(length=255), nullable=False),
    sa.Column('ExtensionProgramId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ExtensionProgramId'], ['ExtensionProgram.ExtensionProgramId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ProjectId')
    )
    op.create_table('Admin',
    sa.Column('AdminId', sa.String(length=36), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('LoginId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['LoginId'], ['Login.LoginId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AdminId')
    )
    op.create_table('User',
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('MiddleName', sa.String(length=50), nullable=True),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('ContactDetails', sa.String(length=13), nullable=False),
    sa.Column('Birthdate', sa.Date(), nullable=False),
    sa.Column('Gender', sa.String(length=20), nullable=False),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('LoginId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['LoginId'], ['Login.LoginId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('Beneficiary',
    sa.Column('BeneficiaryId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('BeneficiaryId')
    )
    op.create_table('Student',
    sa.Column('VolunteerId', sa.String(length=36), nullable=False),
    sa.Column('SkillsInterest', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['VolunteerId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('VolunteerId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student')
    op.drop_table('Beneficiary')
    op.drop_table('User')
    op.drop_table('Admin')
    op.drop_table('Project')
    op.drop_table('Login')
    op.drop_table('Role')
    op.drop_table('ExtensionProgram')
    # ### end Alembic commands ###
