"""add certificate model

Revision ID: 0f9f01378433
Revises: bdbacfb984af
Create Date: 2023-11-16 05:42:43.344818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9f01378433'
down_revision = 'bdbacfb984af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Certificate',
    sa.Column('CertificateId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('ProjectId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProjectId'], ['Project.ProjectId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('CertificateId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Certificate')
    # ### end Alembic commands ###
