"""add foreign key on Activity model

Revision ID: 1d0db7da3842
Revises: dd584cf19b62
Create Date: 2023-09-09 15:20:25.080721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0db7da3842'
down_revision = 'dd584cf19b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ProjectId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Project', ['ProjectId'], ['ProjectId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ProjectId')

    # ### end Alembic commands ###
