"""Fix Announcement

Revision ID: 2ea707a6ee4f
Revises: 57664ec8c743
Create Date: 2023-09-05 14:49:31.288449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea707a6ee4f'
down_revision = '57664ec8c743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Announcement',
    sa.Column('AnnouncementId', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Content', sa.Text(), nullable=True),
    sa.Column('CreatorId', sa.String(length=36), nullable=False),
    sa.Column('isLive', sa.Boolean(), nullable=False),
    sa.Column('Slug', sa.String(length=255), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=False),
    sa.Column('Updated', sa.DateTime(), nullable=False),
    sa.Column('ExtensionProgramId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CreatorId'], ['Admin.AdminId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ExtensionProgramId'], ['ExtensionProgram.ExtensionProgramId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AnnouncementId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Announcement')
    # ### end Alembic commands ###
