"""Change program model name

Revision ID: 2f2a7c2188a9
Revises: 70dbca6913bd
Create Date: 2023-08-27 18:14:25.496923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2a7c2188a9'
down_revision = '70dbca6913bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Program',
    sa.Column('ProgramId', sa.Integer(), nullable=False),
    sa.Column('ProgramName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ProgramId')
    )
    op.drop_table('program')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('ProgramId', sa.INTEGER(), server_default=sa.text('nextval(\'"program_ProgramId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ProgramName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ProgramId', name='program_pkey')
    )
    op.drop_table('Program')
    # ### end Alembic commands ###
