"""change activity foreign key in survey model

Revision ID: 36654b554930
Revises: e4813a965f9e
Create Date: 2023-10-18 00:27:33.638986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36654b554930'
down_revision = 'e4813a965f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Survey', schema=None) as batch_op:
        batch_op.drop_constraint('Survey_ActivityId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Activity', ['ActivityId'], ['ActivityId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Survey', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Survey_ActivityId_fkey', 'Project', ['ActivityId'], ['ProjectId'], ondelete='CASCADE')

    # ### end Alembic commands ###
