"""Add status and image to project and activity

Revision ID: 46fc028611e0
Revises: a4b38a45f476
Create Date: 2023-09-24 14:27:56.999542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fc028611e0'
down_revision = 'a4b38a45f476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImageUrl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ImageFileId', sa.Text(), nullable=True))

    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('ImageUrl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ImageFileId', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('ImageFileId')
        batch_op.drop_column('ImageUrl')
        batch_op.drop_column('Status')

    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_column('ImageFileId')
        batch_op.drop_column('ImageUrl')

    # ### end Alembic commands ###
