"""empty message

Revision ID: 4fe85abc5139
Revises: 2ea707a6ee4f
Create Date: 2023-09-05 20:08:56.957283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe85abc5139'
down_revision = '2ea707a6ee4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsLive', sa.Boolean(), nullable=False))
        batch_op.drop_column('isLive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isLive', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('IsLive')

    # ### end Alembic commands ###
