"""empty message

Revision ID: 50d438813b92
Revises: 9598fa8e1657
Create Date: 2023-10-09 23:42:21.701581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d438813b92'
down_revision = '9598fa8e1657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Abbreviation', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Program', schema=None) as batch_op:
        batch_op.drop_column('Abbreviation')

    # ### end Alembic commands ###
