"""Rename column

Revision ID: 66490fe22b01
Revises: 8de666b0104b
Create Date: 2023-09-01 03:55:42.344040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66490fe22b01'
down_revision = '8de666b0104b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NumberOfBeneficiaries', sa.Integer(), nullable=False))
        batch_op.drop_column('NumberOfBenificiaries')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NumberOfBenificiaries', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('NumberOfBeneficiaries')

    # ### end Alembic commands ###
