"""add collaborator model, change backref to back_populates

Revision ID: 6d77ae8577dd
Revises: 81d3e8bb071a
Create Date: 2023-10-13 12:23:23.046433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d77ae8577dd'
down_revision = '81d3e8bb071a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Collaborator',
    sa.Column('CollaboratorId', sa.Integer(), nullable=False),
    sa.Column('Organization', sa.String(length=100), nullable=False),
    sa.Column('KeyPersonnel', sa.String(length=100), nullable=False),
    sa.Column('Location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('CollaboratorId')
    )
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ProposedBudget', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('ApprovedBudget', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('CollaboratorId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Collaborator', ['CollaboratorId'], ['CollaboratorId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('CollaboratorId')
        batch_op.drop_column('ApprovedBudget')
        batch_op.drop_column('ProposedBudget')

    op.drop_table('Collaborator')
    # ### end Alembic commands ###
