"""Add Program model

Revision ID: 70dbca6913bd
Revises: e39ca1f270a8
Create Date: 2023-08-27 18:10:43.803035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70dbca6913bd'
down_revision = 'e39ca1f270a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('ProgramId', sa.Integer(), nullable=False),
    sa.Column('ProgramName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ProgramId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program')
    # ### end Alembic commands ###
