"""make admin and faculty subtype of user

Revision ID: 732f86bcfbdd
Revises: 7c962d717ce7
Create Date: 2023-10-01 19:37:58.236091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732f86bcfbdd'
down_revision = '7c962d717ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.drop_constraint('Admin_LoginId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['AdminId'], ['UserId'], ondelete='CASCADE')
        batch_op.drop_column('FirstName')
        batch_op.drop_column('LastName')
        batch_op.drop_column('LoginId')

    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.drop_constraint('Faculty_LoginId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['FacultyId'], ['UserId'], ondelete='CASCADE')
        batch_op.drop_column('FirstName')
        batch_op.drop_column('LastName')
        batch_op.drop_column('LoginId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LoginId', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('LastName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('FirstName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Faculty_LoginId_fkey', 'Login', ['LoginId'], ['LoginId'], ondelete='CASCADE')

    with op.batch_alter_table('Admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LoginId', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('LastName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('FirstName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Admin_LoginId_fkey', 'Login', ['LoginId'], ['LoginId'], ondelete='CASCADE')

    # ### end Alembic commands ###
