"""temp activity model

Revision ID: 7b1ac4e986f8
Revises: 2f2a7c2188a9
Create Date: 2023-08-29 18:15:35.953383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1ac4e986f8'
down_revision = '2f2a7c2188a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('activity_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    # ### end Alembic commands ###
