"""Add Faculty model

Revision ID: 7c962d717ce7
Revises: 46fc028611e0
Create Date: 2023-09-30 19:57:37.845671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c962d717ce7'
down_revision = '46fc028611e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Faculty',
    sa.Column('FacultyId', sa.String(length=36), nullable=False),
    sa.Column('FirstName', sa.String(length=50), nullable=False),
    sa.Column('LastName', sa.String(length=50), nullable=False),
    sa.Column('LoginId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['LoginId'], ['Login.LoginId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FacultyId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Faculty')
    # ### end Alembic commands ###
