"""empty message

Revision ID: 81d3e8bb071a
Revises: 50d438813b92
Create Date: 2023-10-09 23:50:32.461748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d3e8bb071a'
down_revision = '50d438813b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Program', schema=None) as batch_op:
        batch_op.alter_column('Abbreviation',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Program', schema=None) as batch_op:
        batch_op.alter_column('Abbreviation',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
