"""Registration model

Revision ID: 84d95ef1cd7e
Revises: 0ba363175fff
Create Date: 2023-09-07 18:18:03.645360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d95ef1cd7e'
down_revision = '0ba363175fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Registration',
    sa.Column('RegistrationId', sa.Integer(), nullable=False),
    sa.Column('RegistrationDate', sa.Date(), nullable=False),
    sa.Column('ProjectId', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ProjectId'], ['Project.ProjectId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['User.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RegistrationId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Registration')
    # ### end Alembic commands ###
