"""Fix foreignkey issue in ExtensionProgram

Revision ID: 8de666b0104b
Revises: d3cfe56e68f9
Create Date: 2023-08-31 19:18:44.030533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de666b0104b'
down_revision = 'd3cfe56e68f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AgendaId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ProgramId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Program', ['ProgramId'], ['ProgramId'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Agenda', ['AgendaId'], ['AgendaId'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ProgramId')
        batch_op.drop_column('AgendaId')

    # ### end Alembic commands ###
