"""make lead proponent as foreign key

Revision ID: 9598fa8e1657
Revises: 732f86bcfbdd
Create Date: 2023-10-01 20:50:30.197110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9598fa8e1657'
down_revision = '732f86bcfbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LeadProponentId', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['LeadProponentId'], ['UserId'], ondelete='CASCADE')
        batch_op.drop_column('LeadProponent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LeadProponent', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('LeadProponentId')

    # ### end Alembic commands ###
