"""Add columns for image in ExtensionProgram

Revision ID: a4b38a45f476
Revises: c0641e835a9a
Create Date: 2023-09-23 21:04:08.920337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b38a45f476'
down_revision = 'c0641e835a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Activity_Date'), ['Date'], unique=False)

    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Announcement_Created'), ['Created'], unique=False)
        batch_op.create_index(batch_op.f('ix_Announcement_IsLive'), ['IsLive'], unique=False)
        batch_op.create_index(batch_op.f('ix_Announcement_Updated'), ['Updated'], unique=False)

    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ImageUrl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ImageFileId', sa.Text(), nullable=True))

    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.drop_constraint('Login_Email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_Login_Email'), ['Email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Login_Email'))
        batch_op.create_unique_constraint('Login_Email_key', ['Email'])

    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.drop_column('ImageFileId')
        batch_op.drop_column('ImageUrl')

    with op.batch_alter_table('Announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Announcement_Updated'))
        batch_op.drop_index(batch_op.f('ix_Announcement_IsLive'))
        batch_op.drop_index(batch_op.f('ix_Announcement_Created'))

    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Activity_Date'))

    # ### end Alembic commands ###
