"""add attendance model

Revision ID: bdbacfb984af
Revises: 66f9ca6c5f66
Create Date: 2023-11-14 17:35:54.869804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbacfb984af'
down_revision = '66f9ca6c5f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Attendance',
    sa.Column('AttendanceId', sa.Integer(), nullable=False),
    sa.Column('HasAttended', sa.Boolean(), nullable=True),
    sa.Column('BeneficiaryId', sa.String(length=36), nullable=False),
    sa.Column('ActivityId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ActivityId'], ['Activity.ActivityId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiary.BeneficiaryId'], ),
    sa.PrimaryKeyConstraint('AttendanceId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Attendance')
    # ### end Alembic commands ###
