"""Remove activity, Add Agenda

Revision ID: d3cfe56e68f9
Revises: 7b1ac4e986f8
Create Date: 2023-08-31 19:09:44.219033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cfe56e68f9'
down_revision = '7b1ac4e986f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agenda',
    sa.Column('AgendaId', sa.Integer(), nullable=False),
    sa.Column('AgendaName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AgendaId')
    )
    op.drop_table('activity')
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.drop_column('Agenda')
        batch_op.drop_column('Program')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ExtensionProgram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Program', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Agenda', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('activity_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activity_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='activity_pkey')
    )
    op.drop_table('Agenda')
    # ### end Alembic commands ###
