"""modify Activity model

Revision ID: dd584cf19b62
Revises: 84d95ef1cd7e
Create Date: 2023-09-09 11:13:37.503968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd584cf19b62'
down_revision = '84d95ef1cd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.String(length=255), nullable=False))
        batch_op.drop_column('ActivityFlow')
        batch_op.drop_column('CommunityBackground')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CommunityBackground', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ActivityFlow', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('Description')

    # ### end Alembic commands ###
