"""add models for survey

Revision ID: e4813a965f9e
Revises: 5a5b94fa34b0
Create Date: 2023-10-18 00:24:07.609031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4813a965f9e'
down_revision = '5a5b94fa34b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Question',
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('Text', sa.Text(), nullable=False),
    sa.Column('State', sa.Integer(), nullable=False),
    sa.Column('Type', sa.Integer(), nullable=False),
    sa.Column('Required', sa.Integer(), nullable=False),
    sa.Column('Responses', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('QuestionId')
    )
    op.create_table('Survey',
    sa.Column('SurveyId', sa.Integer(), nullable=False),
    sa.Column('SurveyName', sa.Text(), nullable=False),
    sa.Column('ActivityId', sa.Integer(), nullable=False),
    sa.Column('State', sa.Integer(), nullable=False),
    sa.Column('Questions', sa.Text(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ActivityId'], ['Project.ProjectId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SurveyId')
    )
    op.create_table('Response',
    sa.Column('ResponseId', sa.Integer(), nullable=False),
    sa.Column('BeneficiaryId', sa.String(length=36), nullable=False),
    sa.Column('SurveyId', sa.Integer(), nullable=False),
    sa.Column('QuestionId', sa.Integer(), nullable=False),
    sa.Column('Text', sa.Text(), nullable=True),
    sa.Column('Num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BeneficiaryId'], ['Beneficiary.BeneficiaryId'], ),
    sa.ForeignKeyConstraint(['QuestionId'], ['Question.QuestionId'], ),
    sa.ForeignKeyConstraint(['SurveyId'], ['Survey.SurveyId'], ),
    sa.PrimaryKeyConstraint('ResponseId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Response')
    op.drop_table('Survey')
    op.drop_table('Question')
    # ### end Alembic commands ###
