"""add attributes for certificate file in certificate model

Revision ID: ebaed73ce61b
Revises: 0f9f01378433
Create Date: 2023-11-16 14:55:42.391902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebaed73ce61b'
down_revision = '0f9f01378433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CertificateUrl', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('CertificateFileId', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Certificate', schema=None) as batch_op:
        batch_op.drop_column('CertificateFileId')
        batch_op.drop_column('CertificateUrl')

    # ### end Alembic commands ###
